const Error = error{
    unexpected_result,
};
const main = fn() Error!void {
    var a: s32 = 5;
    var b: s32 = 4;
    if (a * b - a * b != 0) {
        return Error.unexpected_result;
    }
}
