const Error = error{
    unexpected_result,
};
const main = fn() Error!void {
    const dividend: s32 = 30;
    const divisor: s32 = 6;
    const div: s32 = dividend / divisor;
    const n: s32 = 5;

    if (n - div != 0) {
        return Error.unexpected_result;
    }
}
