const Error = error{
    unexpected_result,
};

const main = fn() Error!void {
    var a: s32 = 561;
    var b: s32 = 124;
    var c: s32 = a ^ b;
    var d: s32 = a ^ b;
    if (c ^ d != 0) {
        return Error.unexpected_result;
    }
}
